{% set name = "quickseries" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quickseries-{{ version }}.tar.gz
  sha256: 2d0ef37294a9bb92d8009b0d340b54787d512957f7acb89702852db87e9324c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - pip
  run:
    - python >=3.11
    - dustgoggles
    - numpy
    - scipy
    - sympy

test:
  imports:
    - quickseries
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/millionconcepts/quickseries.git
  summary: generate fast approximations of mathematical functions
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - m-stclair
