{% set name = "quickseries" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quickseries-{{ version }}.tar.gz
  sha256: 3f71945d977bfcb8d409df63f14c5490b843f6fddfbc09d99020ea041fe15844

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - pip
  run:
    - python >=3.11
    - dustgoggles
    - numpy
    - scipy
    - sympy

test:
  imports:
    - quickseries
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/millionconcepts/quickseries.git
  summary: generate fast approximations of mathematical functions
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - m-stclair
